### ISSUE TITLE
Wrong behavior when 'values' object isn't created

### ISSUE THREAD

**Issue by Explodey54** [lukeed/webpack-plugin-replace#3]
When there is a 'pattern' object, but no 'value' object, plugin replace included files with `undefined`

**Comment by lukeed** [comment]
I would call this user error & say it's fine as is. The plugin allows multiple formats:

* Pass `patterns` with `{ regex, value }`shape; or
* Pass `patterns` and `values` separately

If you don't define any values for replacement, then yes, technically it's undefined 😉
